name: EXAM CI/CD 

on: [push, workflow_dispatch]

jobs:
  build-container:
    name: Build-container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'
    - name: Build and push to DockerHub
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: vmikhalskyi/exam:latest

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_JSON }}'
      
    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '${{ secrets.GCP_INSTANCE }}'
        zone: '${{ secrets.GCP_ZONE }}'
        ssh_private_key: '${{ secrets.GCP_SSH_KEY }}'
        command: 'sudo docker pull vmikhalskyi/exam && sudo docker run -it vmikhalskyi/exam:latest 3'